
 <?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new Question';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('forum', array('action' => 'add')));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 ?>
 <table>
    <tr>
        <td><?php echo $this->formRow($form->get('question')); ?></td>
    </tr>
     <tr>
        <td><?php echo $this->formSubmit($form->get('submit')); ?></td>
    </tr>
 </table>


 <?php echo $this->form()->closeTag(); ?>

