<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My Forum';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('forum', array('action'=>'add'));?>">Add new Question</a>
 </p>

 <table class="table">
 <tr>
     <th>Ques No.</th>
     <th>Questions</th>
     <th>Actions</th>
 </tr>
 
 <?php  foreach ($forum as $forum) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($forum->id);?></td>
     <td><?php echo $this->escapeHtml($forum->question);?></td>
     <td>
         <a href="<?php echo $this->url('forum',
             array('action'=>'view', 'id' => $forum->id));?>">See Answers</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>