<?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Answers';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <h2><?php echo $this->escapeHtml($forum->question);?></h2>
<table class="table">
<?php
foreach ($answer as $answer) : ?>

 <tr>
     <td><?php echo $this->escapeHtml($answer->id);?></td>
     <td><?php echo $this->escapeHtml($answer->answer);?></td>
     <td><?php echo $this->escapeHtml($answer->likes)." Likes";?></td>
     <td><a href="<?php echo $this->url('forum',
             array('action'=>'view', 'id' => $forum->id));?>">Like Answer</a></td>
 </tr>
 <?php endforeach; ?>
</table>
<?php
 $form->setAttribute('action', $this->url('forum', array('action' => 'view','id' => $forum->id)));
 $form->prepare();
 $form->get('quesid')->setValue((int)$forum->id);
 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formHidden($form->get('quesid'));
 ?>
 <table>
    <tr>
        <td><?php echo $this->formRow($form->get('answer')); ?></td>
    </tr>
     <tr>
        <td><?php echo $this->formSubmit($form->get('submit')); ?></td>
    </tr>
 </table>


 <?php echo $this->form()->closeTag(); ?>
 