<h1>You Can't see me !!</h1> 
 <?php

 $authform->setAttribute('action', $this->url('auth', array('action' => '')));
 $authform->prepare();
 
 echo $this->form()->openTag($authform);
 ?>
 <table>
    <tr>
        <td><?php echo $this->formRow($authform->get('username')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formRow($authform->get('password')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formSubmit($authform->get('submit')); ?></td>
    </tr>
 </table>
 <?php  foreach ($userdetail as $user) : ?>

     <td><?php echo $this->escapeHtml($user->id);?></td>
     <td><?php echo $this->escapeHtml($user->username);?></td>
  
 <?php endforeach; ?>