 <?php
 include_once "header.phtml";
 if(!isset($_SESSION['base']['username'])){
    $authform->setAttribute('action', $this->url('auth', array('action' => '')));
    $authform->prepare();
 ?> <h1>You Can't see me !!</h1>  <?php
 echo $this->form()->openTag($authform);
 ?>
 <div class="well">
  <div align="right">
    <?php if($this->errormsg !=""){ ?>
  <div class="alert alert-danger"> <?php echo $this->escapeHtml($errormsg); ?></div>
  <?php } ?>
 <table>
    <tr>
        <td><?php echo $this->formRow($authform->get('username')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formRow($authform->get('password')); ?></td>
    </tr>
     <tr>
        <td><a href="<?php echo $this->url('auth',
             array('action'=>'resetpassword'));?>">Forgot Password?</a><br/></td>
    </tr>
    <tr>
        <td><?php echo $this->formSubmit($authform->get('submit')); ?>
        Or <a href="<?php echo $this->url('auth',
             array('action'=>'registration'));?>">Register Yourself</a>
        </td>
    </tr>
   
 </table>
 </div>
  </div>
 <?php  }else{
      header('Cache-Control: max-age=900'); // to prevent document Expired
      ?> <h1>You Can see me !!</h1> <?php
     echo "<h2>Welcome ".$_SESSION['base']['username']."</h2>";
    ?>
    <a href="<?php echo $this->url('profile',
             array('action'=>'user','id'=>$_SESSION['base']['username']));?>">Check Your Details</a><br/>
    
 <?php } ?>