
 <?php
 
 if(!isset($_SESSION['base']['username'])){
    $authform->setAttribute('action', $this->url('auth', array('action' => '')));
    $authform->prepare();
 ?> <h1>You Can't see me !!</h1>  <?php   
 echo $this->form()->openTag($authform);
 ?>
 <table>
    <tr>
        <td><?php echo $this->formRow($authform->get('username')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formRow($authform->get('password')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->formSubmit($authform->get('submit')); ?></td>
    </tr>
    <tr>
        <td> Or <a href="<?php echo $this->url('auth',
             array('action'=>'registration'));?>">Register Yourself</a><br/></td>
    </tr>
 </table>
 <?php  }else{
      header('Cache-Control: max-age=900'); // to prevent document Expired
      ?> <h1>You Can see me !!</h1> <?php
     echo "<h2>Welcome ".$_SESSION['base']['username']."</h2>";
    ?>
    <a href="<?php echo $this->url('auth',
             array('action'=>'dashboard'));?>">Check Your Details</a><br/>
    
     <a href="<?php echo $this->url('auth',
             array('action'=>'logout'));?>">Log Out</a>
    
 <?php } ?>