
 <?php
 if(!isset($_SESSION['base']['username'])){
       header("Location:https://www.google.com");
    }else{
      ?> <h1>You Can see me !!</h1> <?php
      echo "<h2>Welcome ".$_SESSION['base']['username']."</h2>";
      echo "<h3>Your Email is <span style='color:#c0f'>".$_SESSION['base']['email']."</span></h3>";
    ?>
  <a href="<?php echo $this->url('auth',
             array('action'=>'logout'));?>">Log Out</a>
    
 <?php } ?>