 
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?php echo $this->url('home') ?>">My World</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form method="post" class="navbar-form navbar-left" role="search" action="<?php echo $this->url('auth', array('action' => 'search')) ?>">
        <div class="form-group">
          <input type="text" name="searchitem" class="form-control" placeholder="Search User" required>
        </div>
          <button type="submit" class="btn btn-success">Search</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <?php if(isset($_SESSION['base']['username'])){ ?>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <?php echo $_SESSION['base']['username']; ?><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<?php echo $this->url('auth',
             array('action'=>''));?>">Home</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li> <a href="<?php echo $this->url('auth',
             array('action'=>'logout'));?>">Log Out</a></li>
          </ul>
        </li>
        <?php }?>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
